#!/usr/bin/env bash
set -euo pipefail

export ARCH=arm64 SUBARCH=arm64
export KBUILD_BUILD_HOST=GitHub-Actions
export KBUILD_BUILD_USER=ci-builder

make -j1 O=out clean mrproper
make -j1 O=out ARCH=arm64 vendor/meteoric_defconfig

cat > ksu_ci.config << 'EOF'
#
# ksu_ci.config – minimal overrides for Meteoric Kernel v6 (SM8475)
#

# ----------- KernelSU & SuSFS -----------

# KernelSU Next

CONFIG_KSU=y
CONFIG_KSU_DEBUG=n
CONFIG_KSU_ALLOWLIST_WORKAROUND=n
CONFIG_KSU_LSM_SECURITY_HOOKS=y

# KernelSU Next - susfs

CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
CONFIG_KSU_SUSFS_SUS_SU=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y
CONFIG_KSU_SUSFS_TRY_UMOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=n
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y

# Make sure OverlayFS is on
CONFIG_OVERLAY_FS=y
# ------------ OPTIMIZATIONS ------------

# Project Matrixx scheduler & performance
CONFIG_CASS_SCHED=y
CONFIG_SCHED_TUNE=y
CONFIG_SCHED_BOOST=y
CONFIG_CPU_INPUT_BOOST=y
CONFIG_CPU_INPUT_BOOST_DURATION_MS=150
CONFIG_CPU_INPUT_BOOST_FREQ_LP=1248000
CONFIG_CPU_INPUT_BOOST_FREQ_PERF=2304000
CONFIG_HZ=300

# Tickless power-saving
CONFIG_NO_HZ_FULL=y
CONFIG_NO_HZ_IDLE=y

# ZRAM built-in for swap
CONFIG_ZRAM=y
CONFIG_ZRAM_DEF_COMP_LZ4=y
CONFIG_FRONTSWAP=y

# Enforce BBR as default TCP congestion  
CONFIG_DEFAULT_TCP_CONG="bbr2"

# Preserve 32-bit compatibility for vendor blobs
CONFIG_COMPAT_VDSO=y
CONFIG_THUMB2_COMPAT_VDSO=y
CONFIG_KUSER_HELPERS=y

# Disable debug/sanitizer for production
CONFIG_UBSAN=n
CONFIG_KASAN=n
EOF

make -j1 O=out CC=clang ARCH=arm64 vendor/meteoric_defconfig ksu_ci.config savedefconfig
rm -f ksu_ci.config
