#!/usr/bin/env bash
set -euo pipefail

export ARCH=arm64 SUBARCH=arm64
export KBUILD_BUILD_HOST=GitHub-Actions
export KBUILD_BUILD_USER=ci-builder

# Clean and initialize configuration
make -j1 O=out clean mrproper
make -j1 O=out ARCH=$ARCH vendor/meteoric_defconfig

# Generate optimized config for Nothing Phone 2 (SM8475)
cat > ksu_ci.config << 'EOF'
# KernelSU-Next & SUSFS
CONFIG_KSU=y
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_MODULE=y
CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y

# Meteoric optimizations
CONFIG_CPU_INPUT_BOOST=y
CONFIG_CPU_INPUT_BOOST_DURATION_MS=250
CONFIG_CPU_INPUT_BOOST_FREQ_LP=1036800
CONFIG_CPU_INPUT_BOOST_FREQ_PERF=1536000

# Scheduler
CONFIG_CASS_SCHED=y
CONFIG_SCHED_WALT=y
CONFIG_SCHED_TUNE=y
CONFIG_SCHED_BOOST=y

# Performance & power
CONFIG_LTO_CLANG_THIN=y
CONFIG_LTO_CLANG_THIN_RAMSIZE=128
CONFIG_PREEMPT_NONE=y
CONFIG_HZ=300
CONFIG_NO_HZ_FULL=y
CONFIG_NO_HZ_IDLE=y
CONFIG_CPU_IDLE_GOV_MENU=y

# Thermal & freq
CONFIG_THERMAL=y
CONFIG_THERMAL_GOV_STEP_WISE=y
CONFIG_CPU_THERMAL=y
CONFIG_DEVFREQ_THERMAL=y
CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_INTERACTIVE=y

# Memory & I/O
CONFIG_VMAP_STACK=y
CONFIG_ZRAM=y
CONFIG_ZRAM_DEF_COMP_LZ4=y
CONFIG_ZRAM_MEMORY_TRACKING=y
CONFIG_FRONTSWAP=y
CONFIG_CMA=y
CONFIG_ZSMALLOC=y
CONFIG_MGLRU=y
CONFIG_IOSCHED_MAPLE=y
CONFIG_BFQ_GROUP_IOSCHED=y
CONFIG_DEFAULT_IOSCHED="maple"

# Networking
CONFIG_TCP_CONG_BBR=y
CONFIG_TCP_CONG_BBR2=y
CONFIG_DEFAULT_TCP_CONG="bbr2"

# ARM64 & security
CONFIG_ARM64_PTR_AUTH=y
CONFIG_ARM64_BTI=y
CONFIG_ARCH_RANDOM=y
CONFIG_ARM64_CRYPTO=y
CONFIG_HARDENED_USERCOPY=y
CONFIG_SLAB_FREELIST_RANDOM=y
CONFIG_SLAB_FREELIST_HARDENED=y
CONFIG_STACKPROTECTOR_STRONG=y
CONFIG_SHADOW_CALL_STACK=y

# Optional sanitizers (development)
CONFIG_UBSAN=y
CONFIG_UBSAN_TRAP=y
CONFIG_UBSAN_BOUNDS=y

# Display, audio & filesystems
CONFIG_DRM_MSM=y
CONFIG_FB_MSM_MDSS=y
CONFIG_SND_SOC_WCD938X=y
CONFIG_SOUND_CONTROL=y
CONFIG_F2FS_FS=y
CONFIG_EXT4_USE_FOR_EXT2=y

# Subsystems & features
CONFIG_CGROUPS=y
CONFIG_NAMESPACES=y
CONFIG_USER_NS=y
CONFIG_KSU_NEXT=y
CONFIG_SUSFS_VERSION=154
CONFIG_HBM_FOD_OPTIMIZATION=y
CONFIG_WIRELESS_CHARGING_CONTROL=y
CONFIG_HAPTIC_INTENSITY_CONTROL=y
CONFIG_KCAL=y
CONFIG_KLAPSE=y

# Battery & charging
CONFIG_QCOM_BATTERY_CHARGER=y
CONFIG_SMB1390_CHARGE_PUMP=y
CONFIG_BATTERY_BCL=y
CONFIG_QTI_QBG=y
EOF

# Generate the final config and clean up
make -j1 O=out CC=clang ARCH=$ARCH vendor/meteoric_defconfig ksu_ci.config savedefconfig
rm -f ksu_ci.config
